/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmshome;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author aksha
 */
public class chevrolet extends javax.swing.JFrame {

    /**
     * Creates new form chevrolet
     */
    public chevrolet() {
        initComponents();
        this.setSize(1024,683);
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        try{
   
                    Class.forName("java.sql.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/football_management_team?&useSSL=false","root","root");
                    Statement st=conn.createStatement();
                    
                    String query="Select * from Sponsors where Spons_ID=13;";
                    ResultSet rs=st.executeQuery(query);
                    while(rs.next())
                    {
                        //jlt2.setText(rs.getString("Spons_ID"));
                        JL.setText("NAME OF SPONSOR:  "+rs.getString("Name"));
                        JL1.setText("INVESTMENTS:  "+rs.getString("Investment"));
                        JL3.setText("LENGTH OF CONTRACT:  "+rs.getString("Length_of_Contract"));
                    }
            }   
        catch(Exception e)
        {
               JOptionPane.showMessageDialog(this,e.getMessage()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL = new javax.swing.JLabel();
        JL1 = new javax.swing.JLabel();
        JL3 = new javax.swing.JLabel();
        JL2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(1000, 675));
        getContentPane().setLayout(null);

        JL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JL.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JL);
        JL.setBounds(20, 10, 980, 140);

        JL1.setBackground(new java.awt.Color(255, 255, 255));
        JL1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JL1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JL1);
        JL1.setBounds(20, 490, 980, 140);

        JL3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JL3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JL3);
        JL3.setBounds(20, 260, 980, 140);

        JL2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JL2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JL2);
        JL2.setBounds(780, 290, 220, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/chevrolet.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 683);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chevrolet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chevrolet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chevrolet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chevrolet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chevrolet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL;
    private javax.swing.JLabel JL1;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JL3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
