package dbmshome;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aksha
 */
public class Deledet2 extends javax.swing.JFrame {

    /**
     * Creates new form Deledet2
     */
    public Deledet2() {
        initComponents();
        F1.setRowHeight(30);
        this.setSize(1920,1080);
        JTableHeader header = F1.getTableHeader();
        header.setFont(new Font("Tahoma", Font.PLAIN, 14));
    }
    
        void Show_User()
    {
        DefaultTableModel model1=(DefaultTableModel)F1.getModel();
          
       try{
                    Class.forName("java.sql.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/football_management_team?&useSSL=false","root","root");
                    Statement st=conn.createStatement();
                    
                    String query="Select * from Fixtures;";
                    ResultSet rs=st.executeQuery(query);
                    
                     while(rs.next()){
                        String d1=rs.getString("FID");
                        String d2=rs.getString("Home_Team");
                        String d3=rs.getString("Away_Team");
                        String d4=rs.getString("Score");
                        String d5=rs.getString("Date");
                       
                                
                        model1.addRow(new Object[] {d1,d2,d3,d4,d5});                       
                        
                         
                        
                        

                            }
                     
                     
                            rs.close();
                            
                            st.close();
                            conn.close();
                            }
                                catch(Exception e){
                                        JOptionPane.showMessageDialog(this,e.getMessage());

                                    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        U1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        U2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        U3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        U4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        U5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        F1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/delete.png"))); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(880, 740, 175, 80);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  FIXTURES DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(820, 60, 330, 43);

        U1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        U1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U1ActionPerformed(evt);
            }
        });
        getContentPane().add(U1);
        U1.setBounds(430, 240, 300, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FID");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 250, 116, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOME_TEAM");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 330, 129, 25);

        U2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        U2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U2ActionPerformed(evt);
            }
        });
        getContentPane().add(U2);
        U2.setBounds(430, 320, 300, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AWAY_TEAM");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 400, 131, 25);

        U3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        U3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U3ActionPerformed(evt);
            }
        });
        getContentPane().add(U3);
        U3.setBounds(430, 400, 300, 35);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SCORE");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 490, 116, 25);

        U4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(U4);
        U4.setBounds(430, 490, 300, 35);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DATE");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 590, 116, 25);

        U5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        U5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U5ActionPerformed(evt);
            }
        });
        getContentPane().add(U5);
        U5.setBounds(430, 590, 300, 35);

        F1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        F1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FID", "Home_Team", "Away_Team", "Score", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        F1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(F1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1180, 250, 670, 346);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/united1.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1965, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
                    
                    Class.forName("java.sql.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/football_management_team?&useSSL=false","root","root");
                    int row=F1.getSelectedRow();
                   
                    String value=(F1.getModel().getValueAt(row,0).toString());
                    
                    String query="Delete from Fixtures where FID="+value;
                    
                    
                    
                    PreparedStatement st=conn.prepareStatement(query);
                    
                    
                    st.executeUpdate();
                    DefaultTableModel model=(DefaultTableModel)F1.getModel();
                    model.setRowCount(0);
                    Show_User();
                    
                   
                   
        
                    
                    
                    
                    
                     
                    JOptionPane.showMessageDialog(null,"Data has been Deleted");
                    U1.setText(" ");
                    U2.setText(" ");
                    U3.setText(" ");
                    U4.setText(" ");
                    U5.setText(" ");
                    
        
        
        }
        
        
        catch(Exception e){
                                        JOptionPane.showMessageDialog(this,e.getMessage());
        
        }              
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void U1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U1ActionPerformed

    private void U2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U2ActionPerformed

    private void U3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U3ActionPerformed

    private void U5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U5ActionPerformed

    private void F1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F1MouseClicked
          DefaultTableModel model2=(DefaultTableModel)F1.getModel();
        int row=F1.getSelectedRow();
        U1.setText(model2.getValueAt(row,0).toString());
        U2.setText(model2.getValueAt(row,1).toString());
        U3.setText(model2.getValueAt(row,2).toString());
        U4.setText(model2.getValueAt(row,3).toString());
        U5.setText(model2.getValueAt(row,4).toString());
              
        
        
        
        
    }//GEN-LAST:event_F1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deledet2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deledet2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deledet2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deledet2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deledet2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable F1;
    private javax.swing.JTextField U1;
    private javax.swing.JTextField U2;
    private javax.swing.JTextField U3;
    private javax.swing.JTextField U4;
    private javax.swing.JTextField U5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
