/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmshome;

/**
 *
 * @author Ankit
 */
public class Gallery extends javax.swing.JFrame {

    static int imgc=0;
    /**
     * Creates new form Gallery
     */
    public Gallery() {
        initComponents();
        this.setSize(1920,1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        la = new javax.swing.JLabel();
        ra = new javax.swing.JLabel();
        gal4 = new javax.swing.JLabel();
        gal3 = new javax.swing.JLabel();
        gal2 = new javax.swing.JLabel();
        gal1 = new javax.swing.JLabel();
        galbg = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        la.setFont(new java.awt.Font("Tahoma", 1, 76)); // NOI18N
        la.setForeground(new java.awt.Color(255, 255, 255));
        la.setText("<");
        la.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laMouseExited(evt);
            }
        });
        getContentPane().add(la);
        la.setBounds(30, 440, 70, 60);

        ra.setFont(new java.awt.Font("Tahoma", 1, 76)); // NOI18N
        ra.setForeground(new java.awt.Color(255, 255, 255));
        ra.setText(">");
        ra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raMouseExited(evt);
            }
        });
        getContentPane().add(ra);
        ra.setBounds(1840, 450, 62, 60);

        gal4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/gal4.JPG"))); // NOI18N
        gal4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "The 2016 Europa League Victory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(gal4);
        gal4.setBounds(450, 210, 970, 660);
        gal4.setVisible(false);

        gal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/gal3.jpg"))); // NOI18N
        gal3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1999 Historic Treble Win", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(gal3);
        gal3.setBounds(590, 220, 660, 530);
        gal3.setVisible(false);

        gal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/gal2.jpg"))); // NOI18N
        gal2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "The 2013 Premier League Triumph", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(gal2);
        gal2.setBounds(460, 220, 962, 660);
        gal2.setVisible(false);

        gal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/gal1.jpg"))); // NOI18N
        gal1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "The 2016 FA Cup Victory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(gal1);
        gal1.setBounds(460, 200, 960, 670);

        galbg.setFont(new java.awt.Font("Tahoma", 1, 76)); // NOI18N
        galbg.setForeground(new java.awt.Color(255, 255, 255));
        galbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/galbg.jpg"))); // NOI18N
        getContentPane().add(galbg);
        galbg.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raMouseEntered
ra.setForeground(java.awt.Color.RED);        // TODO add your handling code here:
    }//GEN-LAST:event_raMouseEntered

    private void raMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raMouseExited
ra.setForeground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_raMouseExited

    private void laMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laMouseEntered
la.setForeground(java.awt.Color.RED);        // TODO add your handling code here:
    }//GEN-LAST:event_laMouseEntered

    private void laMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laMouseExited
la.setForeground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_laMouseExited

    private void raMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raMouseClicked
        imgc++;
switch(imgc)
{
    case 0: gal1.setVisible(true);
            gal2.setVisible(false);
            gal3.setVisible(false);
            gal4.setVisible(false);
            break;
            
    case 1: gal1.setVisible(false);
            gal2.setVisible(true);
            gal3.setVisible(false);
            gal4.setVisible(false);
            break;
    case 2: gal1.setVisible(false);
            gal2.setVisible(false);
            gal3.setVisible(true);
            gal4.setVisible(false);
            break;
    case 4: gal1.setVisible(false);
            gal2.setVisible(false);
            gal3.setVisible(false);
            gal4.setVisible(true);
            break;
            
    }//GEN-LAST:event_raMouseClicked
    if(imgc>3)
        imgc=3;
    }
    private void laMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laMouseClicked
      imgc--;
switch(imgc)
{
    case 0: gal1.setVisible(true);
            gal2.setVisible(false);
            gal3.setVisible(false);
            gal4.setVisible(false);
            break;
            
    case 1: gal1.setVisible(false);
            gal2.setVisible(true);
            gal3.setVisible(false);
            gal4.setVisible(false);
            break;
    case 2: gal1.setVisible(false);
            gal2.setVisible(false);
            gal3.setVisible(true);
            gal4.setVisible(false);
            break;
    case 4: gal1.setVisible(false);
            gal2.setVisible(false);
            gal3.setVisible(false);
            gal4.setVisible(true);
            break;
            
    }                               
    if(imgc<0)
        imgc=0;
      // TODO add your handling code here:
    }//GEN-LAST:event_laMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gallery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gal1;
    private javax.swing.JLabel gal2;
    private javax.swing.JLabel gal3;
    private javax.swing.JLabel gal4;
    private javax.swing.JLabel galbg;
    private javax.swing.JLabel la;
    private javax.swing.JLabel ra;
    // End of variables declaration//GEN-END:variables
}
