/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmshome;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ankit
 */
public class Home extends javax.swing.JFrame {

    GoalKeepers gk=new GoalKeepers();
    Defenders df=new Defenders();
    Midfielders mf=new Midfielders();
    Forwards fw=new Forwards();
    HeadCoaches hc=new HeadCoaches();
    Results res=new Results();
    MedicalStaff ms=new MedicalStaff();
    AssistantCoaches ac=new AssistantCoaches();
    UpcomingFixtures uf=new UpcomingFixtures();
    static Login lg=new Login();
    Scouts ss=new Scouts();
    adidas ads=new adidas();
    aboutus as=new aboutus();
    
    
   // JComboBox jComboBox1;    /**
    /* Creates new form Home
     */
    public Home() {
        initComponents();
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        label1 = new java.awt.Label();
        choice1 = new java.awt.Choice();
        choice2 = new java.awt.Choice();
        choice3 = new java.awt.Choice();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bgnd = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(java.awt.SystemColor.textHighlight);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        choice1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        choice1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        choice1.setPreferredSize(new java.awt.Dimension(45, 30));
        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });
        getContentPane().add(choice1);
        choice1.setBounds(530, 520, 230, 40);
        choice1.add("Players");
        choice1.add("Goal Keepers");
        choice1.add("Defenders");
        choice1.add("Midfielders");
        choice1.add("Forwards");

        choice2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        choice2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice2ItemStateChanged(evt);
            }
        });
        getContentPane().add(choice2);
        choice2.setBounds(1160, 520, 210, 40);
        choice2.add("Fixtures");
        choice2.add("Upcoming Fixtures");
        choice2.add("Results");

        choice3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        choice3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice3ItemStateChanged(evt);
            }
        });
        getContentPane().add(choice3);
        choice3.setBounds(850, 520, 220, 40);
        choice3.add("Coaches");
        choice3.add("Head Coaches");
        choice3.add("Assistant Coaches");
        choice3.add("Medical Staff");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/spo1.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 190, 210, 130);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/spo4.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 860, 300, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/spo3.jpg"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 460, 230, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/spo2.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 670, 190, 80);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  ADMIN LOGIN");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1690, 900, 210, 40);

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("LOGIN");
        jButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton1StateChanged(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1740, 950, 120, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome to the Manchester United Football Club. ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 750, 1010, 45);

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("This is the place for you to access all the information ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 800, 1090, 45);

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("about the club,the players and the coaches.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 850, 900, 45);

        jLabel7.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FANS");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1570, 40, 90, 40);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GALLERY");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1340, 40, 140, 40);

        jLabel10.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SCOUTS");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1740, 40, 130, 40);

        jLabel13.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ABOUT US");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1100, 40, 170, 40);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GALLERY");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1340, 40, 140, 40);

        Bgnd.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        Bgnd.setForeground(new java.awt.Color(255, 255, 255));
        Bgnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmshome/united.jpg"))); // NOI18N
        Bgnd.setText("Developed by Akshay and Ankit Kulkarni");
        Bgnd.setOpaque(true);
        getContentPane().add(Bgnd);
        Bgnd.setBounds(0, 0, 2180, 1080);

        getAccessibleContext().setAccessibleName("Home Page");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        lg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged

        
        
    }//GEN-LAST:event_jButton1StateChanged

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
          String sel=choice1.getSelectedItem();
          DefaultTableModel model=null;
        String query=" ";
        
        switch(sel)
        {
            case "Defenders" : df.setVisible(true);
                                  model=(DefaultTableModel)df.P1.getModel(); 
                                  query="Select * from Player where Position='CB' OR Position='RB';";
                                  model.setRowCount(0);
                                  break;
                                
            case "Midfielders" : mf.setVisible(true);
                                       model=(DefaultTableModel)mf.P2.getModel();
                                       query="Select * from Player where Position='CM' OR Position='RM' OR Position='CAM' OR Position='CDM' OR Position='RW' OR Position='LW';";
                                       model.setRowCount(0);
                                       break;
                                       
            case "Forwards" :  fw.setVisible(true);
                                    model=(DefaultTableModel)fw.F1.getModel();
                                    query="Select * from Player where Position='ST' OR Position='RW' OR Position='LW';";
                                    model.setRowCount(0);
                                    break;
                                 
            case "Goal Keepers" :    gk.setVisible(true);
                                    model=(DefaultTableModel)gk.G1.getModel();
                                    query="Select * from Player where Position='GK';";
                                    model.setRowCount(0);
                                    break;                    
                                       
        }
          
          try{
                    Class.forName("java.sql.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/football_management_team?&useSSL=false","root","root");
                    Statement st=conn.createStatement();
                    
                    
                    
                    ResultSet rs=st.executeQuery(query);
                        
                        
                        while(rs.next()){
                        String d1=rs.getString("Name");
                        String d2=rs.getString("Position");
                        String d3=rs.getString("Nationality");
                        String d4=rs.getString("Age");
                        model.addRow(new Object[] {d1,d2,d3,d4});                       
                        
                         
                        
                        

                            }
                     
                     
                            rs.close();
                            
                            st.close();
                            conn.close();
                            }
                                catch(Exception e){
                                        JOptionPane.showMessageDialog(this,e.getMessage());

                                    }

         

    }//GEN-LAST:event_choice1ItemStateChanged

    private void choice3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice3ItemStateChanged
        String sel=choice3.getSelectedItem();
        DefaultTableModel model=null;
        String query=" ";
        
        switch(sel)
        {
            case "Head Coaches" : hc.setVisible(true);
                                  model=(DefaultTableModel)hc.P4.getModel(); 
                                  query="Select * from Coach where Designation='Head Coach';";
                                  model.setRowCount(0);
                                  break;
                                
            case "Assistant Coaches" : ac.setVisible(true);
                                       model=(DefaultTableModel)ac.A1.getModel();
                                       query="Select * from Coach where Designation='Assistant Coach';";
                                       model.setRowCount(0);
                                       break;
                                       
            case "Medical Staff" :  ms.setVisible(true);
                                    model=(DefaultTableModel)ms.M1.getModel();
                                    query="Select * from Medical_Staff;";
                                    model.setRowCount(0);
                                    break;
                                       
        }
            
          
          try{
                    Class.forName("java.sql.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/football_management_team?&useSSL=false","root","root");
                    Statement st=conn.createStatement();
                    
                    
                    ResultSet rs=st.executeQuery(query);
                        
                        
                        while(rs.next()){
                        String d1=rs.getString("Name");
                        String d2=rs.getString("Designation");
                        
                        String d3=rs.getString("Age");
                        String d4=rs.getString("Gender");
                        model.addRow(new Object[] {d1,d2,d3,d4});                       
                        
                         
                        
                        

                            }
                     
                     
                            rs.close();
                            
                            st.close();
                            conn.close();
                            }
                                catch(Exception e){
                                        JOptionPane.showMessageDialog(this,e.getMessage());

                                    }
                    
        
        
         
    }//GEN-LAST:event_choice3ItemStateChanged

    private void choice2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice2ItemStateChanged
        // TODO add your handling code here:
        String sel=choice2.getSelectedItem();
         DefaultTableModel model=null;
         int flagrs=0,flaguf=0;
         
        String query=" ";
       
        switch(sel)
        {
            case "Results" : res.setVisible(true);
                              
                                  model=(DefaultTableModel)res.R1.getModel(); 
                                  query="Select * from Fixtures where not Score='NIL';";
                                  model.setRowCount(0);
                                
                                  break;
                                
            case "Upcoming Fixtures" :uf.setVisible(true);
                                      
                                       model=(DefaultTableModel)uf.U1.getModel();
                                       query="Select * from Fixtures where Score='NIL';";
                                       model.setRowCount(0);
                                       break;
         
        }
         
         
         
         
         
         
         try{
                    Class.forName("java.sql.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/football_management_team?&useSSL=false","root","root");
                    Statement st=conn.createStatement();                   
                    ResultSet rs=st.executeQuery(query);
                    
                     while(rs.next()){
                        String d1=rs.getString("Home_Team");
                        String d2=rs.getString("Away_Team");
                        String d3=rs.getString("Score");
                        String d4=rs.getString("Date");
                        model.addRow(new Object[] {d1,d2,d3,d4});                       
                        
                         
                        
                        

                            }
                     
                     
                            rs.close();
                            
                            st.close();
                            conn.close();
                            }
                                catch(Exception e){
                                        JOptionPane.showMessageDialog(this,e.getMessage());

                                    }
        
        
         
    }//GEN-LAST:event_choice2ItemStateChanged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
Gallery gal=new Gallery();
gal.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
jLabel1.setForeground(java.awt.Color.RED);             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
jLabel1.setForeground(java.awt.Color.WHITE);             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
jLabel7.setForeground(java.awt.Color.RED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
jLabel7.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
Fans fan=new Fans();
fan.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
jLabel10.setForeground(Color.RED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
  jLabel10.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
       
new adidas().setVisible(true);

                    
                    
                    
                    
                    
                    
                    
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
new chevrolet().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
new aon().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
new dhl().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
    ss.setVisible(true); 
    DefaultTableModel model=(DefaultTableModel)ss.S1.getModel();
        try{
                    Class.forName("java.sql.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/football_management_team?&useSSL=false","root","root");
                    Statement st=conn.createStatement();
                    
                    String query="Select * from Scouts;";
                    ResultSet rs=st.executeQuery(query);
                    
                     while(rs.next()){
                        String d1=rs.getString("SID");
                        String d2=rs.getString("Name");
                        String d3=rs.getString("Nationality");
                        String d4=rs.getString("Region");
                        
                                
                        model.addRow(new Object[] {d1,d2,d3,d4});                       
                        
                         
                        
                        

                            }
                     
                     
                            rs.close();
                            
                            st.close();
                            conn.close();
                            }
                                catch(Exception e){
                                        JOptionPane.showMessageDialog(this,e.getMessage());

                                    }// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
       
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
jLabel13.setForeground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        jLabel13.setForeground(Color.white);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        as.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bgnd;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private java.awt.Choice choice3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
